# theme: jekyll-theme-minimal
remote_theme: nkymut/just-the-docs
# https://github.com/mmistakes/minimal-mistakes
# remote_theme: "mmistakes/minimal-mistakes@4.24.0"

show_downloads: "true"
google_analytics: G-GX0HTR3LCT
ga_tracking: G-GX0HTR3LCT

layout: page
title: ""
summary: p5.jsでデジタル刺繍
logo: https://nkymut.github.io/p5-advent-2023/assets/lissajous_plex2.jpg
image: /assets/lissajous.jpg
summary_large_image: /assets/fractal_xtree.jpg
date: 09/12/2023

# Aux links for the upper right navigation
# aux_links:
#   "microbit-webueb-p5js on GitHub":
#     - "//github.com/nkymut/microbit-webusb-p5js"
#   "microbit-webble-p5js on GitHub":
#     - "//github.com/nkymut/microbit-webble-p5js"


# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Turn on incremental building to reduce overall build time (still in beta)
# See: https://jekyllrb.com/docs/configuration/incremental-regeneration/
incremental: true

twitter:
  username: nkymuta
  card: summary_large_image
  image: /assets/lissajous.jpg
  summary_large_image:  /assets/fractal_xtree.jpg
  summary: p5.jsでデジタル刺繍
